name: dompetcare
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Dependencies aplikasi kamu
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.20.2
  uuid: ^4.5.2
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.6
  table_calendar: ^3.2.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # --- TAMBAHAN BARU DI SINI ---
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# --- KONFIGURASI IKON DI SINI ---
# Pastikan kamu sudah menaruh file gambar di: assets/icon/icon.png
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21
